### ISSUE TITLE
contig name changed too lower case in bam.py --> contig name not found in header

### ISSUE THREAD

**Issue by envanloo** [betteridiot/bamnostic#25]
When using the Random access sample:

import bamnostic as bs
bam = bs.AlignmentFile("yourfile.bam", 'rb')
for i, read in enumerate(bam.fetch(contig="Scaffold_Name", start=1, stop=100)):
   if i >= 3:
       break
   print(read)

bamnostic gives the error that 'scaffold_name" is not found in the header. Of course not, as the name has capitals.
**To Reproduce**
1. Make your own bam file with contig names containing capitals
2. Run the above python lines
3. You will get a message that the contig with a name in only lower case is not found.

**Expected behavior**
Bamnostic should keep the literal name of the contig and not change to lower case.

**Desktop (please complete the following information):**
 - Win 6 64x
 - Python Version:  3.7 using Spyder 3.3.1
 - bamnostic Version: 1.0.0

**Additional context**
Problem seems to be the line in bam.py:
        query = parse_region(**signature)

contig in bam.py is a str with the capital still in place
query.contig has the same value but now in lower case only
re-assigning contig to query.contig solved the problem:

query.contig=contig

in the line just after query = parse_region(**signature)

**Comment by betteridiot** [comment]
Thank you for bringing this to my attention. It seems pretty straightforward. I will try to take a look at this later today,

**Comment by betteridiot** [comment]
This should be fixed as of [v1.0.1](https://github.com/betteridiot/bamnostic/releases/latest/). The details of the fix can be found in the commit above.
