### ISSUE TITLE
CSI indexing support as well as BAI indexing

### ISSUE THREAD

**Issue by peterjc** [betteridiot/bamnostic#3]
Is there any plan to support CSI indexing? This adds a number of benefits over BAI which has a fixed binning tree and a hard coded maximum reference length, making it unsuitable for many genomes (e.g. lots of plants, some marsupials).

**Comment by betteridiot** [comment]
As stated in openjournals/joss-reviews#826, CSI indexing suffers the same fate as CRAM format: not that it is too complex, but it is still too new. While it is a successor to BAI indexing, it has not permeated the domain to the degree that BAI has yet. There are plans to incorporate it as the community grows around bamnostic, but we still believe bamnostic is impactful in its current state as well.
