### ISSUE TITLE
core.py has a self.self which should be a self. only

### ISSUE THREAD

**Issue by ThomasH-RGB** [betteridiot/bamnostic#34]
The last line in the following property in core.py should use self._qa_end, not self.self
    @property
    def query_alignment_end(self):
        """One past the final index position of the aligned portion of the read

        `query_alignment_*` all refer to the portion of the read that was aligned,
        and therefore exclude clipping, but include insertions.
        """
        return self.self.__qa_end

**Comment by betteridiot** [comment]
You are correct.

**Comment by betteridiot** [comment]
Fixed in c573dc940b5
