### ISSUE TITLE
CRAM support?

### ISSUE THREAD

**Issue by peterjc** [betteridiot/bamnostic#4]
The HTSlib team are pushing CRAM as the successor to BAM. This is a much more complicated format, so are there any plans to support that here?

**Comment by betteridiot** [comment]
I also agree with you that CRAM support would be a great boon for bamnostic. However, like you stated, it is a much more complex format that would require a non-trivial expenditure of time and resources to write up. Not saying that this feature is not in the future of bamnostic, but we believe that the present form of bamnostic could still be a very impactful tool for current pipelines and analysis.

**Comment by peterjc** [comment]
That's what I expected - I suggest adding something to the README file which should preempt m repeats of my question.

**Comment by betteridiot** [comment]
Noted. Thank you

**Comment by betteridiot** [comment]
14747e7135260c69a77b2908e187faaaacf95ef7 added documentation to the README.md Stating that CRAM & CSI support was not available at this time.
