### ISSUE TITLE
AlignedSegment object has no attribute 'reference_name'

### ISSUE THREAD

**Issue by castrocp** [betteridiot/bamnostic#41]
**Describe the bug**
When attempting to access the 'reference_name' for a read that was unmapped, rather than returning `*`, bamnostic returns:
` AttributeError: 'AlignedSegment' object has no attribute 'reference_name' `

**To Reproduce**
```
if re.match('\*', row.reference_name):   
    print('unmapped read')
```

**Expected behavior**
When attempting to access the 'reference_name' for an unmapped read, I would expect `*` to be returned

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-45-generic x86_64)
 - Python Version: Python 3.7.6
 - bamnostic Version: 1.1.4

**Comment by betteridiot** [comment]
Fixed by #44
