### ISSUE TITLE
Pyscript-Pyodide-PyPI wheel request

### ISSUE THREAD

**Issue by AngelicaLindlof** [betteridiot/bamnostic#53]
I am currently investigating how to use Pyscript for creating a GUI based on HTML for my Python program. My program uses bamnostic to parse BAM files. However, Pyscript is based on Pyodide and requires that a Python package has a wheel available in PyPI.

I am therefore wondering if it is possible for you to create a wheel for bamnostic and make it available in PyPI and/or Pyodide?

Regards, Angelica

**Comment by betteridiot** [comment]
Thank you for suggesting this. I needed to push an update to fix an indexing issue anyways. I will try to address this as soon as possible.
