### ISSUE TITLE
Enable handling of SAM files with `bs.AlignmentFile`

### ISSUE THREAD

**Issue by akikuno** [betteridiot/bamnostic#54]
**Is your feature request related to a problem? Please describe.**

I try to use bamnostic for [cstag-cli](https://github.com/akikuno/cstag-cli) to read BAM/SAM files, but when the input file is SAM, `bs.AlignmentFile` returns an error, indicating it does not handle SAM.

**Describe the solution you'd like**

I understand bamnostic is primarily designed for parsing BAM, not SAM.
However, if `bs.AlignmentFile` could read SAM files in a manner similar to pysam, it would be beneficial (If it's feasible, I would prefer to use bamnostic instead of pysam).

**Describe alternatives you've considered**

None

**Additional context**

Here is a simple example to reproduce the error.

```python
import bamnostic as bs
from pathlib import Path

sam_content = "@SQ\tSN:chr1\tLN:1000\n"
path_sam_file = Path("test2.sam")
path_sam_file.write_text(sam_content)

bs.AlignmentFile(path_sam_file, "r")
"""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kuno/miniconda/envs/test-cstag/lib/python3.12/site-packages/bamnostic/core.py", line 158, in __init__
    assert "b" in mode.lower(), "BAM files must be used in binary mode"
AssertionError: BAM files must be used in binary mode
"""
```

If there's anything I've overlooked or any workaround available, I would greatly appreciate it if you could kindly inform me.

**Comment by betteridiot** [comment]
I appreciate you considering using `bamnostic` within your package. I suspect that this is in response to https://github.com/akikuno/cstag-cli/issues/4. I am sorry if I was misunderstood in that post. I was stating that the dependency issues were the reason that I created `bamnostic` in the first place. I was providing this as an anecdote. I was not suggesting that you use `bamnostic` though since it *only* works with BAM files...thus the name.

**Comment by akikuno** [comment]
Thank you very much for your kind response.
I have been experiencing installation errors due to pysam dependencies, and I was quite interested in using bamnostic with cstag-cli if feasible. However, for the time being, I will continue to use pysam and plan to add documentation about potential issues.
Thank you so much for your support!
