### ISSUE TITLE
Support CIGARs with >65535 operations in BAM files

### ISSUE THREAD

**Issue by peterjc** [betteridiot/bamnostic#6]
See https://github.com/samtools/hts-specs/issues/40 and the specification update in https://github.com/samtools/hts-specs/pull/227

**Comment by betteridiot** [comment]
6e55d648ecfbf8a01332c3ef160c9be8b556c1e5 provides support for CIGARs >65535 operations

**Comment by betteridiot** [comment]
This was tested on the example file provided by @lh3 in the samtools/hts-specs#40 thread
