### ISSUE TITLE
Put bgzf.py under 3-clause BSD

### ISSUE THREAD

**Issue by peterjc** [betteridiot/bamnostic#9]
See https://github.com/biopython/biopython/commit/93ff47b5399b4e1d83815b2d075e2070ad98ba9f#diff-8f35ada1444d6f77e41c86b649ba88ec 

You can now use bgzf.py under the 3-clause BSD licence like the rest of your codebase, and clean up the header.

**Comment by betteridiot** [comment]
Thank you. This was updated in aba7f695e5135ecd90e3a53908ba9b6b8c767129
